### ISSUE TITLE
Consider specifying "origin private file system"-ness on each "file system locator"

### ISSUE THREAD

**Issue by a-sully** [whatwg/fs#103]
Context: https://github.com/whatwg/fs/pull/96#discussion_r1130265157
Related to #92

The cleanest way to do this would be to give each locator an optional Storage Bucket (see [WICG/storage-buckets](https://github.com/WICG/storage-buckets)), though that API is not yet standardized

**Comment by annevk** [comment]
Can we check that the first item in path is the empty string as per https://github.com/whatwg/fs/pull/96#issuecomment-1471523968? I realize that is a tad magical so we could define some kind of predicate for it that has a note alongside explaining the situation.
