### ISSUE TITLE
Sandboxed application file system

### ISSUE THREAD

**Issue by hydroper** [whatwg/fs#115]
Adobe AIR supports a file system API which allows a rich-internet application to access the app's self installation directory (files that ship with the rich-internet application) and the app's private data directory (similiar to cookies or local storage).

- `app:` URLs
  - RIA's installation directory
- `app-storage:` URLs
  - RIA's storage directory

Is there something similiar for the web? I know it's possible to emulate at least the app's private data directory with indexedDB (there's inclusively a NPM package for this), but it's not efficient I think and anyway there's currently no way to access the app's installation directory.

### User permission for writting large files to `app-storage:`

indexedDB, localStorage and cookies have a short file size limit. Could the browser ask the user if the RIA is allowed to use large size files for `app-storage:` file storage?

**Comment by tomayac** [comment]
Closest to that is probably the [origin private file system](https://developer.chrome.com/articles/origin-private-file-system/). It’s specified in the [File System Living Standard](https://fs.spec.whatwg.org/).

**Comment by hydroper** [comment]
> Closest to that is probably the [origin private file system](https://developer.chrome.com/articles/origin-private-file-system/). It’s specified in the [File System Living Standard](https://fs.spec.whatwg.org/).

That should cover `app-storage:`! But it seems the article doesn't cover about the file size limit. Is there a permission prompt to ask the user to allow large storage files?

**Comment by hydroper** [comment]
About `app:`:

- The origin private file system can kind of achieve `app:` besides `app-storage:`.
- The origin private file system can't access files that ship with a standalone app that is built in, like, say, Electron; so emulating `app:` with that API doesn't go well.

**Comment by tomayac** [comment]
File size limits are bound to the [storage quota of a storage shelf](https://storage.spec.whatwg.org/#storage-quota).

**Comment by a-sully** [comment]
On browsers which support it, https://wicg.github.io/file-system-access/ allows you to read/write files on the local file system (without being subject to the browser's quota limits), but it's not exactly a 1:1 replacement since it's not possible to pre-load access to any specific files (see https://github.com/WICG/file-system-access/issues/235 for example)
