### ISSUE TITLE
Are my messages be stored in file system 

### ISSUE THREAD

**Issue by jayok1234** [whatwg/fs#162]
### What is the issue with the File System Standard?

I'm not receiving calls or text messages to my device. I want to ensure messages aren't being disbursed from file system. All messages should come straight to my number or apps. Please remove any and all restrictions on my device. This is awful. I don't even use Google files

**Comment by HolgerJeromin** [comment]
This repo has nothing to do with Google files or even one single program. 
What ever your problem is, this is not caused by the content of this repo...

**Comment by jayok1234** [comment]
What about this being blocked? Does this affect my device services
