### ISSUE TITLE
Migration of File System Access issues applicable to File System

### ISSUE THREAD

**Issue by annevk** [whatwg/fs#2]
Any issues that apply to the text in this standard filed at https://github.com/WICG/file-system-access/issues should be moved over.

**Comment by janvarga** [comment]
This is already being discussed here: https://github.com/WICG/file-system-access/issues/323

People are actually requesting fully sync OPFS surface.

**Comment by a-sully** [comment]
I believe that's the last of the issues relevant to this standard! All migrated issues have been closed on the WICG side with a comment redirecting any further conversation here.

**Comment by annevk** [comment]
Thanks @a-sully! Much appreciated.
