### ISSUE TITLE
Seek target range

### ISSUE THREAD

**Issue by jesup** [whatwg/fs#31]
the webidl has 
`[[EnforceRange](https://webidl.spec.whatwg.org/#EnforceRange)] required [unsigned long long](https://webidl.spec.whatwg.org/#idl-unsigned-long-long) at;`

However the WPT test of negative seek targets for SyncAccessHandles looks for dom NotSupportedError; the webidl spec says it should throw a TypeError.    Likely this is simply a bug in the WPT test

**Comment by a-sully** [comment]
Yup, that's an error. Looks like the Chrome implementation was missing the `[EnforceRange]` in our idl file, which caused this to slip through the cracks. I have [patch](https://github.com/web-platform-tests/wpt/pull/34240) up to fix this and update the WPT

**Comment by a-sully** [comment]
After thinking about this a bit more, we might want to consider what the other end of the target range looks like, as well. Using an `unsigned long long` makes sense to guarantee the value is non-negative, but most operating systems do not support offsets of more than the max `long long` (`off_t`  is signed, for example). And 32-bit OSes may not even support more than the max `long`. 

Should we have language in the spec about what to do if the value is not valid for file operations on that OS? (`InvalidModificationError`? `TypeError`?)

**Comment by a-sully** [comment]
The WPT has [been updated](https://github.com/web-platform-tests/wpt/pull/34240) to throw a `TypeError` if a negative value is passed, but I'll leave this issue open for the discussion of what we should do when an offset is passed which is too large for the underlying OS to handle

**Comment by annevk** [comment]
Using a `TypeError` as well seems reasonable.

**Comment by a-sully** [comment]
Thoughts on `NotSupportedError`, since whether the value is supported as an offset may depend on the OS? (sorry, I'm not sure whether this is consistent with how the error code is used elsewhere.) Otherwise `TypeError` seems reasonable to me  :)

**Comment by annevk** [comment]
That could work as well, to some extent this depends on whether we expect web developers to branch on the exception type. If we don't, using the generic exception is preferred (that's `TypeError` to be clear).

I don't think we'd expect web developers to branch here. At least not based on this, but I could be mistaken. It seems to me that if the OS limit needs to be exposed there are better ways to do that, e.g., through a static getter.
