### ISSUE TITLE
close() method missing?

### ISSUE THREAD

**Issue by ronburk** [whatwg/fs#44]
I'm a little confused by the fact that closing is mentioned many times as a concept, it appears there is a close() method that I'm calling successfully under Chrome, and yet I don't see any actual explicit documentation of a close() method.

**Comment by a-sully** [comment]
[`FileSystemWritableFileSteam`](http://go/mdn/API/FileSystemWritableFileStream) (what you get when you call [`handle.createWritable()`](https://fs.spec.whatwg.org/#api-filesystemfilehandle-createwritable)) extends [`WritableStream`](http://go/mdn/API/WritableStream), which has a `close()` method.

`SyncAccessHandle` also has a `close()` method, though specifying this is still a WIP. See #21
