### ISSUE TITLE
Should converting chunk to a FileSystemWriteChunkType refer to IDL type conversion instead?

### ISSUE THREAD

**Issue by EdgarChen** [whatwg/fs#48]
See step 1 of https://fs.spec.whatwg.org/#write-a-chunk
> Let input be the result of [converting](https://infra.spec.whatwg.org/#javascript-string-convert) chunk to a [FileSystemWriteChunkType](https://fs.spec.whatwg.org/#typedefdef-filesystemwritechunktype). If this throws an exception, then return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) that exception.

it refers to https://infra.spec.whatwg.org/#javascript-string-convert which seems wrong, should it refer to https://webidl.spec.whatwg.org/#dfn-convert-ecmascript-to-idl-value instead?

**Comment by a-sully** [comment]
Ah, I believe you're correct there. Would you mind putting up a PR?
