### ISSUE TITLE
Remove w3c.json

### ISSUE THREAD

**Issue by plehegar** [whatwg/fs#5]
https://github.com/whatwg/fs/blob/main/w3c.json is no longer needed (and it's confusing some of our horizontal review tools).

Separately, you'll probably want to update some of the md files (LICENSE, etc.) as well.

https://github.com/w3c/whatwg-coord/issues/12

**Comment by annevk** [comment]
Yeah, #1 will resolve this. Hopefully the final review will happen shortly. Let me know if you need something sooner than that as I can clear some of this up sooner.

**Comment by annevk** [comment]
That has landed now.
