### ISSUE TITLE
truncate() definition doesn't match the non-normative text

### ISSUE THREAD

**Issue by jesup** [whatwg/fs#50]
The text for truncate() on a WritableFileStream doesn't match the non-normative text, such as the discussion of the cursor position.

**Comment by a-sully** [comment]
> The text for truncate() 

Are you talking about the algorithm? (https://fs.spec.whatwg.org/#:~:text=The%20truncate(size,Return%20result) If so, the same issue (of not updating the cursor) also applies to `write()`

**Comment by jesup** [comment]
Yes.  And as you note, there are a bunch of mentions of the cursor in the non-normative text, but 0 references to cursor in the normative text

**Comment by dslee414** [comment]
Closing in factor of https://github.com/whatwg/fs/issues/77
