### ISSUE TITLE
Web IDL syntax error

### ISSUE THREAD

**Issue by autokagami** [whatwg/fs#56]
🤖 This is an automatic issue report for Web IDL syntax error. 🤖

[webidl2.js](https://github.com/w3c/webidl2.js) says:

```
Syntax error at line 4 in fs,4, since `dictionary FileSystemReadWriteOptions`:
 long long at = 0;
                 ^
```

> Error: Required member must not have a default

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

**Comment by annevk** [comment]
@fivedots @a-sully what was the intent here?

**Comment by a-sully** [comment]
I assume the `at` param should not be required. Put up #60 to fix this
