### ISSUE TITLE
Make FileSystemSyncAccessHandle.close algorithm more descriptive

### ISSUE THREAD

**Issue by youennf** [whatwg/fs#83]
It is unclear whether https://fs.spec.whatwg.org/#api-filesystemsyncaccesshandle-close will wait for the lock to be released or will just set the handle state synchronously but will release the lock asynchronously.

**Comment by annevk** [comment]
Yeah, the non-normative description does talk about release, but the normative description doesn't. So currently no lock would be released which seems bogus.

Since everything else is on this object is synchronous I would kinda expect it to wait for release to return?

**Comment by a-sully** [comment]
> So currently no lock would be released which seems bogus.

Yikes

> Since everything else is on this object is synchronous I would kinda expect it to wait for release to return?

Correct. The lock should be released synchronously, before `close()` returns

I'll put up a PR to fix the algorithm soon (after #85 lands, for the sake of avoiding unnecessary merge conflicts)

**Comment by szewai** [comment]
(Since this issue is about making `FileSystemSyncAccessHandle.close` more descriptive, I will just comment here:)

There is a wpt test [fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html](https://wpt.fyi/results/fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html?label=master&label=experimental&aligned) ensuring `close()` is idempotent and I think Chromium does this, but it is not in spec. It would be nice to make it clear.

**Comment by a-sully** [comment]
> There is a wpt test [fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html](https://wpt.fyi/results/fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html?label=master&label=experimental&aligned) ensuring `close()` is idempotent and I think Chromium does this, but it is not in spec. It would be nice to make it clear.

Thanks for bringing this up, @szewai. And you're correct that `close()` is intended to be idempotent and is implemented as such in Chromium. Amusingly, the current spec language is actually correct on that front (`set this.state to "closed"` _is_ idempotent) but this will become _more obviously idempotent_ once we add language to release the lock :)

**Comment by szewai** [comment]
> > There is a wpt test [fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html](https://wpt.fyi/results/fs/FileSystemSyncAccessHandle-close.https.tentative.worker.html?label=master&label=experimental&aligned) ensuring `close()` is idempotent and I think Chromium does this, but it is not in spec. It would be nice to make it clear.
> 
> Thanks for bringing this up, @szewai. And you're correct that `close()` is intended to be idempotent and is implemented as such in Chromium. Amusingly, the current spec language is actually correct on that front (`set this.state to "closed"` _is_ idempotent) but this will become _more obviously idempotent_ once we add language to release the lock :)

My point is we should be clear that this does not throw an InvalidStateError on a second call, as compared to other functions which throws an error when state is closed. Something like "if the state is closed, return; else release lock and set state to closed"

**Comment by annevk** [comment]
Releasing doesn't seem to have an exception opportunity and setting the state to closed doesn't either, so I'm not sure an early return is warranted as it wouldn't be testable. Unless releasing has some side effect I didn't spot.

**Comment by szewai** [comment]
> Releasing doesn't seem to have an exception opportunity and setting the state to closed doesn't either, so I'm not sure an early return is warranted as it wouldn't be testable. Unless releasing has some side effect I didn't spot.

I guess it really depends on the implementation. For example: if the locking is implemented in a different process (process with the AccessHandle needs to message the "LockManager" process to release the "lock"); or if the AccessHandle is backed by a file descriptor, calling close twice could lead to file system error.

I am not sure whether these errors should be observable by websites (whether we should throw exception on such failure), but it seems better to specify that these operations won't be executed twice no matter what the implementation is.

**Comment by a-sully** [comment]
Just to clarify, it sounds like we prefer

```
- if state is closed, return
- set state to closed
- release lock
```
to 
```
- set state to closed
- if lock is held, release lock
```
